import { inviteMemberAction, removeMemberAction, updateMemberRoleAction } from "@/app/actions/foundation";
import { FormButton } from "@/components/form-button";
import { EmptyState, PageHeader } from "@/components/page-header";
import { canManage, requireMembership } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { initials } from "@/lib/utils";

export default async function TeamPage() {
  const { membership } = await requireMembership();
  const members = await prisma.organizationMember.findMany({ where: { organizationId: membership.organizationId }, include: { user: true }, orderBy: [{ role: "asc" }, { createdAt: "asc" }] });
  const allowed = canManage(membership.role);
  return <div className="mx-auto max-w-6xl"><PageHeader eyebrow="Access" title="Team members" description="Owners and admins manage the business. Staff can view the organization without changing its setup." /><div className="grid gap-6 lg:grid-cols-[1fr_360px]"><section className="panel overflow-hidden"><div className="border-b border-[#e4e8e4] px-6 py-5"><h2 className="font-semibold">People with access</h2></div>{members.length === 0 ? <EmptyState title="No team members" description="Invite someone to help manage your workspace." /> : <div className="divide-y divide-[#e7eae7]">{members.map((member) => <div key={member.id} className="flex flex-col gap-4 px-6 py-4 sm:flex-row sm:items-center"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-[#e8efe9] text-xs font-bold text-[#315e50]">{initials(member.user?.name ?? member.invitedName ?? member.invitedEmail)}</span><div className="min-w-0 flex-1"><p className="truncate font-medium">{member.user?.name ?? member.invitedName ?? "Pending member"}</p><p className="truncate text-sm text-[#768079]">{member.invitedEmail} · {member.user ? "Active" : "Pending signup"}</p></div>{member.role === "OWNER" ? <span className="badge">Owner</span> : allowed ? <div className="flex items-center gap-2"><form action={updateMemberRoleAction} className="flex gap-2"><input type="hidden" name="id" value={member.id} /><select name="role" defaultValue={member.role} className="compact-select"><option value="ADMIN">Admin</option><option value="STAFF">Staff</option></select><button className="button button-secondary button-sm">Save</button></form><form action={removeMemberAction}><input type="hidden" name="id" value={member.id} /><button className="button button-danger button-sm">Remove</button></form></div> : <span className="badge">{member.role.toLowerCase()}</span>}</div>)}</div>}</section>{allowed && <aside className="panel h-fit p-6"><h2 className="font-semibold">Invite a team member</h2><p className="mt-1 text-sm leading-5 text-[#768079]">Their membership stays pending until they create a Roomly account with the same email.</p><form action={inviteMemberAction} className="mt-5 space-y-4"><label className="field"><span>Name</span><input name="name" placeholder="Team member" /></label><label className="field"><span>Email</span><input name="email" type="email" required placeholder="person@company.com" /></label><label className="field"><span>Role</span><select name="role"><option value="STAFF">Staff</option><option value="ADMIN">Admin</option></select></label><FormButton className="button button-primary w-full justify-center">Add member</FormButton></form></aside>}</div></div>;
}
