"use client";

import { useActionState } from "react";
import { createBookingAction, rescheduleBookingAction, type BookingFormState } from "@/app/actions/bookings";

export function CreateBookingForm({ resourceId, startsAt, endsAt, slotLabel, timezone }: { resourceId: string; startsAt: string; endsAt: string; slotLabel: string; timezone: string }) {
  const [state, action, pending] = useActionState<BookingFormState, FormData>(createBookingAction, undefined);
  return <form action={action} className="panel grid gap-5 p-6 sm:grid-cols-2 sm:p-8"><input type="hidden" name="resourceId" value={resourceId} /><input type="hidden" name="startsAt" value={startsAt} /><input type="hidden" name="endsAt" value={endsAt} /><div className="rounded-xl bg-[#eaf4df] px-4 py-3 sm:col-span-2"><p className="text-xs font-semibold uppercase tracking-[.12em] text-[#55703f]">Selected time · {timezone}</p><p className="mt-1 font-semibold text-[#274a32]">{slotLabel}</p></div><label className="field"><span>Customer name</span><input name="customerName" required placeholder="Ayesha Khan" /></label><label className="field"><span>Email</span><input name="customerEmail" type="email" required placeholder="customer@example.com" /></label><label className="field"><span>Phone</span><input name="customerPhone" placeholder="+92 300 1234567" /></label><label className="field"><span>Party size</span><input name="partySize" type="number" min={1} defaultValue={1} required /></label><label className="field sm:col-span-2"><span>Customer notes</span><textarea name="customerNotes" rows={3} placeholder="Any requests from the customer" /></label><label className="field sm:col-span-2"><span>Internal notes</span><textarea name="internalNotes" rows={3} placeholder="Visible to staff only" /></label>{state?.error && <p className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700 sm:col-span-2" role="alert">{state.error}</p>}<div className="sm:col-span-2"><button className="button button-primary" disabled={pending}>{pending ? "Creating…" : "Create booking"}</button></div></form>;
}

export function RescheduleBookingForm({ id, startsAt, endsAt, timezone }: { id: string; startsAt: string; endsAt: string; timezone: string }) {
  const [state, action, pending] = useActionState<BookingFormState, FormData>(rescheduleBookingAction, undefined);
  return <form action={action} className="grid gap-4 sm:grid-cols-2"><input type="hidden" name="id" value={id} /><label className="field"><span>Starts · {timezone}</span><input name="startsAt" type="datetime-local" defaultValue={startsAt} required /></label><label className="field"><span>Ends · {timezone}</span><input name="endsAt" type="datetime-local" defaultValue={endsAt} required /></label>{state?.error && <p className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700 sm:col-span-2" role="alert">{state.error}</p>}<div className="sm:col-span-2"><button className="button button-secondary" disabled={pending}>{pending ? "Checking…" : "Reschedule booking"}</button></div></form>;
}
