import { updateOrganizationAdminAction } from "@/app/actions/admin";
import { FormButton } from "@/components/form-button";
import { PageHeader } from "@/components/page-header";
import { prisma } from "@/lib/prisma";

export default async function AdminBusinessesPage() {
  const [organizations, plans] = await Promise.all([
    prisma.organization.findMany({ include: { subscription: { include: { plan: true } }, _count: { select: { members: true, locations: true, resources: true, bookings: true } } }, orderBy: { createdAt: "desc" } }),
    prisma.plan.findMany({ where: { isActive: true }, orderBy: { monthlyPrice: "asc" } }),
  ]);
  return <div><PageHeader eyebrow="Platform administration" title="Businesses" description="Manage access, plans, subscriptions, and support information." /><div className="space-y-4">{organizations.map((organization) => <section key={organization.id} className="panel p-5"><div className="flex flex-col gap-4 border-b border-[#e7ebe7] pb-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2"><h2 className="text-lg font-semibold">{organization.name}</h2><span className={`badge ${organization.isActive ? "badge-green" : "booking-cancelled"}`}>{organization.isActive ? "Active" : "Disabled"}</span></div><p className="mt-1 text-sm text-[#738078]">/{organization.slug} · created {organization.createdAt.toLocaleDateString("en")}</p></div><div className="flex gap-5 text-center text-xs text-[#748078]"><Stat value={organization._count.members} label="Users" /><Stat value={organization._count.locations} label="Locations" /><Stat value={organization._count.resources} label="Spaces" /><Stat value={organization._count.bookings} label="Bookings" /></div></div><form action={updateOrganizationAdminAction} className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><input type="hidden" name="organizationId" value={organization.id} /><label className="field"><span>Plan</span><select name="planId" defaultValue={organization.subscription?.planId ?? plans[0]?.id}>{plans.map((plan) => <option key={plan.id} value={plan.id}>{plan.name} · {plan.currency} {Number(plan.monthlyPrice)}</option>)}</select></label><label className="field"><span>Subscription</span><select name="subscriptionStatus" defaultValue={organization.subscription?.status ?? "ACTIVE"}><option>ACTIVE</option><option>PAUSED</option><option>CANCELLED</option></select></label><label className="field lg:col-span-2"><span>Support information</span><input name="supportNotes" defaultValue={organization.supportNotes ?? ""} placeholder="Account owner, open issue, or support context" /></label><label className="flex w-fit items-center gap-2 rounded-xl border border-[#dce2dd] px-3 py-2 text-sm font-medium"><input type="checkbox" name="isActive" defaultChecked={organization.isActive} /> Organization active</label><div className="sm:col-span-2 lg:col-span-3 lg:text-right"><FormButton className="button button-secondary">Save business controls</FormButton></div></form></section>)}</div></div>;
}

function Stat({ value, label }: { value: number; label: string }) { return <div><p className="text-base font-semibold text-[#27342d]">{value}</p><p>{label}</p></div>; }
